src/Entity/Borrow.php
<?php

namespace App\Entity;

use App\Repository\BorrowRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BorrowRepository::class)]
class Borrow
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_start = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_end = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $return_date = null;

    #[ORM\ManyToOne(inversedBy: 'borrows')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'borrows')]
    private ?ItemsCollection $itemsCollection = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): static
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): static
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->return_date;
    }

    public function setReturnDate(\DateTimeInterface $return_date): static
    {
        $this->return_date = $return_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getItemsCollection(): ?ItemsCollection
    {
        return $this->itemsCollection;
    }

    public function setItemsCollection(?ItemsCollection $itemsCollection): static
    {
        $this->itemsCollection = $itemsCollection;

        return $this;
    }

    public function __toString() {
        return $this->date_start->format('Y-m-d');
    }
}

src/Form/BorrowType.php
<?php

namespace App\Form;

use App\Entity\Borrow;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BorrowType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_start')
            ->add('date_end')
            ->add('return_date')
            ->add('itemsCollection')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Borrow::class,
        ]);
    }
}

src/Controller/BorrowController.php
<?php

namespace App\Controller;

use App\Entity\Borrow;
use App\Form\BorrowType;
use App\Repository\BorrowRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 *
 */
#[Route('/borrow')]
class BorrowController extends AbstractController
{
    /*
     *function to have all the borrowing
     *The BorrowRepository  used to retrieve user-related borrows
     *I put a findBy and not a findAll to retrieve only those of the current user
     */
    #[Route('/', name: 'app_borrow_index', methods: ['GET'])]
    public function index(BorrowRepository $borrowRepository): Response
    {
        return $this->render('borrow/index.html.twig', [
            'borrows' => $borrowRepository->findBy(['user'=>$this->getUser()->getId()]),
        ]);
    }

    /*
     *function to add a borrow
     *request to retrieve the data submitted by the form
     *the EntityManager to be able to persist the data
     *create new instance borrow
     *the response will return the form creation page
     */
    #[Route('/new', name: 'app_borrow_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $borrow = new Borrow();
        $form = $this->createForm(BorrowType::class, $borrow);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $borrow->setUser($this->getUser());
            $entityManager->persist($borrow);
            $entityManager->flush();

            $this->addFlash('success', "Ajout d'emprunt effectué avec succès");
            return $this->redirectToRoute('app_borrow_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('borrow/new.html.twig', [
            'borrow' => $borrow,
            'form' => $form,
        ]);
    }

    /*
     *function for display borrow
     */
    #[Route('/{id}', name: 'app_borrow_show', methods: ['GET'])]
    public function show(Borrow $borrow): Response
    {
        return $this->render('borrow/show.html.twig', [
            'borrow' => $borrow,
        ]);
    }

   /*
    *update Borrow
    * recover the request, recover the borrow, and the manager to be able to send to the database
    */
    #[Route('/{id}/edit', name: 'app_borrow_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Borrow $borrow, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BorrowType::class, $borrow);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            $this->addFlash('success', "Modification effectué avec succès");

            return $this->redirectToRoute('app_borrow_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('borrow/edit.html.twig', [
            'borrow' => $borrow,
            'form' => $form,
        ]);
    }

    /*
     * remove the borrow and redirect after deletion to index page
     * call the instance of the borrow to delete
     */
    #[Route('/{id}', name: 'app_borrow_delete', methods: ['POST'])]
    public function delete(Request $request, Borrow $borrow, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$borrow->getId(), $request->request->get('_token'))) {
            $entityManager->remove($borrow);
            $entityManager->flush();
        }

        $this->addFlash('success', "Suppression effectué avec succès");

        return $this->redirectToRoute('app_borrow_index', [], Response::HTTP_SEE_OTHER);
    }

    /*
     *function for unfinished loans
     *retrieve the parameter value of the current query
     *call the repository function for dates. Using getUser to get the one that concerns the current user
     */
    #[Route('/search/borrow', name: 'app_search_borrow', methods: ['GET', 'POST'])]
    public function search(Request $request, BorrowRepository $borrowRepository): Response
    {

        if ($request->isMethod('GET')) {
            $startDate = $request->query->get('date_start');
            $endDate = $request->query->get('date_end');

            if ($startDate && $endDate) {
                $borrows = $borrowRepository->findBorrowNoFinished($startDate, $endDate, $this->getUser()->getId());
            } else {
                $borrows = [];
            }
        }
        return $this->render('borrow/search.html.twig', [
            'borrows'=>$borrows
        ]);
    }
}

templates/borrow/_delete_form.html.twig
<form method="post" action="{{ path('app_borrow_delete', {'id': borrow.id}) }}" onsubmit="return confirm('Es tu sûr de vouloir supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ borrow.id) }}">
    <button class="btn mr-2 px-4 bg-delete text-black shadow shadow-black border border-black transform -skew-x-12">Supprimer</button>
</form>

templates/borrow/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn my-4 mr-2 px-4 bg-button text-black shadow shadow-black border border-black transform -skew-x-12">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/borrow/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'emprunt{% endblock %}

{% block body %}
    <header class="bg-header h-32 text-white flex items-center fixed top-0 w-full z-50">
        <div class="w-1/4">
            <img class="w-36" src="{{ asset('build/img/logo.png') }}" alt="logo">
        </div>
        <h1 class="text-3xl font-bold text-center flex-1">ANGELIKA LIBRARY</h1>
        <div class="w-1/2 text-right">
            <a class="text-link mr-4" href="{{ path('app_home') }}">Accueil</a>
            <a class="text-link mr-4" href="{{ path('add_item') }}">Ajouter article</a>
            <a class="text-link mr-4" href="{{ path('add_library') }}">Ajouter une librairie</a>
            <a class="text-link mr-4" href="{{ path('app_category_new') }}">Ajouter une Categorie</a>
            <a class="text-link mr-4" href="{{ path('app_library') }}">Library</a>
        </div>
    </header>

    <section class="mt-32">
        <h1 class="w-full text-h1Home text-h1 font-popp text-center mb-8">Modifier l'emprunt</h1>
        <div class="bg-form-gradient mx-auto text-center w-1/2 rounded">
            <div class=" ">
            {{ include('borrow/_form.html.twig', {'button_label': 'Modifier'}) }}
            {{ include('borrow/_delete_form.html.twig') }}
            </div>
            <a href="{{ path('app_borrow_index') }}" class="mr-4">Revenir à la liste</a>
        </div>
    </section>
{% endblock %}

templates/borrow/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunts{% endblock %}

{% block body %}
    <header class="bg-header h-32 text-white flex items-center fixed top-0 w-full z-50">
        <div class="w-1/4">
            <img class="w-36" src="{{ asset('build/img/logo.png') }}" alt="logo">
        </div>
        <h1 class="text-3xl font-bold text-center flex-1">ANGELIKA LIBRARY</h1>
        <div class="w-1/2 text-right">
            <a class="text-link mr-4" href="{{ path('app_home') }}">Accueil</a>
            <a class="text-link mr-4" href="{{ path('app_borrow_new') }}">Créer un nouvel emprunt</a>
            <a class="text-link mr-4" href="{{ path('add_item') }}">Ajouter article</a>
            <a class="text-link mr-4" href="{{ path('add_library') }}">Ajouter une librairie</a>
            <a class="text-link mr-4" href="{{ path('app_library') }}">Library</a>
            <a class="text-link mr-4" href="{{ path('app_category_new') }}">Ajouter une Categorie</a>
            <a class="text-link mr-4" href="{{ path('app_category_index') }}">Catégories</a>
        </div>
    </header>

    <section class="mt-32">
        <h1 class="w-full text-h1Home text-h1 font-popp text-center mb-8">Liste des emprunts</h1>

        {% for borrow in borrows %}
                <div  class="bg-form-gradient  mx-auto w-1/4 p-4 mb-8 rounded">
                    <p><span class="text-center font-semibold m-2">Date de début:</span>{{ borrow.dateStart ? borrow.dateStart|date('Y-m-d') : '' }}</p>
                    <p><span class="text-center font-semibold m-2">Date de fin:</span>{{ borrow.dateEnd ? borrow.dateEnd|date('Y-m-d') : '' }}</p>
                    <p><span class="text-center font-semibold m-2">Date de retour:</span>{{ borrow.returnDate ? borrow.returnDate|date('Y-m-d') : '' }}</p>
                    <p><span class="text-center font-semibold m-2">Titre de l'item:</span>{{ borrow.itemsCollection.title }}</p>
                    <p>
                        <a class=" btn mr-2 px-4 bg-button text-black shadow shadow-black" href="{{ path('app_borrow_show', {'id': borrow.id}) }}">Voir</a>
                        <a class=" btn mr-2 px-4 bg-button text-black shadow shadow-black" href="{{ path('app_borrow_edit', {'id': borrow.id}) }}">Modifier</a>
                    </p>
                </div>
            {% endfor %}
    </section>
{% endblock %}

templates/borrow/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un emprunt{% endblock %}

{% block body %}
    <header class="bg-header h-32 text-white flex items-center fixed top-0 w-full z-50">
        <div class="w-1/4">
            <img class="w-36" src="{{ asset('build/img/logo.png') }}" alt="logo">
        </div>
        <h1 class="text-3xl font-bold text-center flex-1">ANGELIKA LIBRARY</h1>
        <div class="w-1/2 text-right">
            <a class="text-link mr-4" href="{{ path('app_home') }}">Accueil</a>
            <a class="text-link mr-4" href="{{ path('add_item') }}">Ajouter article</a>
            <a class="text-link mr-4" href="{{ path('add_library') }}">Ajouter une librairie</a>
            <a class="text-link mr-4" href="{{ path('app_category_index') }}">Catégories</a>
            <a class="text-link mr-4" href="{{ path('app_library') }}">Library</a>
        </div>
    </header>
    {% for message in app.flashes('success') %}
        <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
            <span class="font-medium">{{ message }}</span>
        </div>
    {% endfor %}
    <section class="mt-32 flex flex-wrap px-4">
        <h1 class="w-full text-h1Home text-h1 font-popp text-center mb-8">Créer un emprunt</h1>
        <div class="bg-form-gradient mx-auto w-1/4  my-4 p-4 mb-4 rounded">
            <div class="flex items-center my-4">
                {{ include('borrow/_form.html.twig') }}
            </div>
            <a href="{{ path('app_borrow_index') }}">Revenir à la liste des emprunts</a>
        </div>
    </section>

{% endblock %}

templates/borrow/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherche d'emprunts{% endblock %}

{% block body %}
    <header class="bg-header h-32 text-white flex items-center fixed top-0 w-full z-50">
        <div class="w-1/4">
            <img class="w-36" src="{{ asset('build/img/logo.png') }}" alt="logo">
        </div>
        <h1 class="text-3xl font-bold text-center flex-1">ANGELIKA LIBRARY</h1>
        <div class="w-1/2 text-right">
            <a class="text-link mr-4" href="{{ path('app_home') }}">Accueil</a>
            <a class="text-link mr-4" href="{{ path('add_item') }}">Ajouter article</a>
            <a class="text-link mr-4" href="{{ path('add_library') }}">Ajouter une librairie</a>
            <a class="text-link mr-4" href="{{ path('app_library') }}">Library</a>
            <a class="text-link mr-4" href="{{ path('app_category_new') }}">Ajouter une Categorie</a>
            <a class="text-link mr-4" href="{{ path('app_category_index') }}">Catégories</a>
        </div>
    </header>

    <section class="mt-32">
        <h1 class="w-full text-h1Home text-h1 font-popp text-center mb-8">Recherche par Emprunts Non Terminés</h1>
    </section>

    <form action="" method='GET' class="w-1/2 text-center mx-auto shadow p-3 mb-5 bg-emerald-50 rounded">
        <div>
            <label for="date_start" class="text-h1Home text-sm font-bold mb-2">Date de début :</label>
            <input type="date" name="date_start" id="date_start">
            <label for="date_end" class="text-h1Home text-sm font-bold mb-2">Date de fin :</label>
            <input type="date" name="date_end" id="date_end">
        </div>
        <input type="submit"
               class="
                        mt-4
                        my-4
                        bg-button
                        text-black
                        shadow
                        shadow-black
                        transform
                        -skew-x-12" value="rechercher">
    </form>

    <div class="bg-form-gradient w-1/3 mx-auto p-4 rounded">
        <h2 class="text-center text-h1Home">Resultats</h2>
        {% if borrows %}
            {% for borrow in borrows %}
                    <p><span class="font-bold m-2">Date de début:</span>{{ borrow.dateStart ? borrow.dateStart|date('Y-m-d') : '' }}</p>
                    <p><span class="font-bold m-2">Date de fin:</span>{{ borrow.dateEnd ? borrow.dateEnd|date('Y-m-d') : '' }}</p>
                    <p><span class="font-bold m-2">Nom de l'item emprunté:</span>{{ borrow.itemsCollection.title }}</p>
                    <p>
                        <a class="btn
                        my-2
                        mr-2
                        px-4
                        bg-button
                        text-black
                        shadow
                        shadow-black
                        border
                        border-black
                        transform skewX(-12deg)"
                           href="{{ path('app_borrow_show', {'id': borrow.id}) }}">Voir</a>
                        <a class="btn
                         my-2
                         mr-2
                         px-4
                         bg-button
                         text-black
                         shadow
                         shadow-black
                          border
                           border-black
                            transform skewX(-12deg)"
                           href="{{ path('app_borrow_edit', {'id': borrow.id}) }}">Modifier</a>
                    </p>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/borrow/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunt{% endblock %}

{% block body %}
    <header class="bg-header h-32 text-white flex items-center fixed top-0 w-full z-50">
        <div class="w-1/4">
            <img class="w-36" src="{{ asset('build/img/logo.png') }}" alt="logo">
        </div>
        <h1 class="text-3xl font-bold text-center flex-1">ANGELIKA LIBRARY</h1>
        <div class="w-1/2 text-right">
            <a class="text-link mr-4" href="{{ path('app_home') }}">Accueil</a>
            <a class="text-link mr-4" href="{{ path('add_item') }}">Ajouter article</a>
            <a class="text-link mr-4" href="{{ path('add_library') }}">Ajouter une librairie</a>
            <a class="text-link mr-4" href="{{ path('app_library') }}">Library</a>
            <a class="text-link mr-4" href="{{ path('app_category_new') }}">Ajouter une Categorie</a>
            <a class="text-link mr-4" href="{{ path('app_category_index') }}">Catégories</a>
        </div>
    </header>

    <section class="mt-32">
        <h1 class="w-full text-h1Home text-h1 font-popp text-center mb-8">Emprunt: {{ borrow.itemsCollection }}</h1>
    </section>

    <div class="bg-form-gradient w-1/3 mx-auto p-4 rounded">
        <p><span class="font-bold m-2">Date de début:</span>{{ borrow.dateStart ? borrow.dateStart|date('Y-m-d') : '' }}</p>
        <p><span class="font-bold m-2">Date de fin:</span>{{ borrow.dateEnd ? borrow.dateEnd|date('Y-m-d') : '' }}</p>
        <div class="flex justify-between p-4">
            <a class=" btn mr-2 px-4 bg-button text-black shadow shadow-black border border-black transform -skew-x-12" href="{{ path('app_borrow_edit', {'id': borrow.id}) }}">Modifier</a>
            {{ include('borrow/_delete_form.html.twig') }}
            <a href="{{ path('app_borrow_index') }}">Revenir à la liste d'emprunts</a>
        </div>

    </div>
{% endblock %}